apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarnexporter.fullname" . }}
  labels:
    {{- include "yarnexporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2517
      protocol: TCP
      name: http
  selector:
    {{- include "yarnexporter.selectorLabels" . | nindent 4 }}
